# Generated by Django 4.2.18 on 2025-02-05 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_review_contributors_and_more'),
        ('authentication', '0004_userfollows'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userfollows',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ReviewContributor',
        ),
    ]
