# Generated by Django 5.1.5 on 2025-01-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_image_delete_cover_rename_cover_review_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
