# Generated by Django 4.2.18 on 2025-02-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_review_contributors_ticket_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='contributors',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='contributors',
        ),
    ]
